const Shoptypes={
    FETCH_COLLECTION_START:'FETCH_COLLECTION_START',
    FETCH_COLLECTION_FAILURE:'FETCH_COLLECTION_FAILURE',
    FETCH_COLLECTION_SUCCESS:'FETCH_COLLECTION_SUCCESS'
}
export default Shoptypes