export const dropdownItemTypes = {
    SET_DROPDOWN_ITEM: "SET_DROPDOWN_ITEM",
    REMOVE_DROPDOWN_ITEM: "REMOVE_DROPDOWN_ITEM",
    REDUCE_DROPDOWN_ITEM: "REDUCE_DROPDOWN_ITEM",
    ADD_DROPDOWN_ITEM: "ADD_DROPDOWN_ITEM",
  };
  